import services.note_m
import services.failures_equipments
import services.alert_vs_closed
import services.down_time
import services.down_time_production_impact
import services.total_failures
import services.equipment_downtime_per_failure
import services.temporally_repair
import services.equipment_pf_segment
import services.equipment_out_off_service
import services.tpef
import services.license
import services.graph_of_assigned_order
import 
