from typing import List
from models import EquipmentOutOffService


def get_equipments_out_off_service() -> List[EquipmentOutOffService]:
    return [
        EquipmentOutOffService(1,
                               "PK-2510",
                               "Empaquetadora de vacío",
                               "10014964",
                               7,
                               3,
                               "10033815",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "20/10/2021"),
        EquipmentOutOffService(2,
                               "TP-1220",
                               "Tapadora de vasos",
                               "10014881",
                               27,
                               2,
                               "10033657",
                               "X",
                               "X",
                               "X",
                               "X",
                               "X",
                               "X",
                               "30/09/2021",
                               "16:59",
                               "30/09/2021",
                               "17:29",
                               "30/09/2021"),
        EquipmentOutOffService(3,
                               "M-2320",
                               "Maquina ceotrifuga descremadora",
                               "10014870",
                               29,
                               2,
                               "10034144",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "28/09/2021"),
        EquipmentOutOffService(4,
                               "P-2250",
                               "Bomba transf. de UDF-4 a homog.(ESF4-S)",
                               "10014756",
                               46,
                               3,
                               "10033643",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "11/09/2021"),
        EquipmentOutOffService(5,
                               "E-3100",
                               "Enfriador de crema",
                               "10014754",
                               47,
                               2,
                               "10033550",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "",
                               "10/09/2021"),
    ]
